name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # Match your project Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        pip install huggingface_hub
        huggingface-cli login --token $HF_TOKEN

    - name: Push to Hugging Face
      run: |
        git config --global user.email "padalasreethika@gmail.com"
        git config --global user.name "SreethikaP"
        git remote add space https://huggingface.co/spaces/SreethikaP/spotify-song-recommendation
        git push space main --force
