data_path: data/songs.csv
model_path: models/kmeans_model.pkl
selected_features:
  - danceability
  - energy
  - valence
  - tempo
  - liveness
  - speechiness
  - acousticness
mlflow_uri: https://dagshub.com/SreethikaP/Song-Recommendation-System.mlflow
